'use strict';
const ENDPOINT='https://coleta-uso-professor-tutor.furukawaluzia.chatgpt.site/api/resumo';
const MATERIALS=[['jogo-a','Fatia do Saber','https://neilasalem.github.io/horizontes/jogo_a.html'],['jogo-b','Encontre a Figura','https://neilasalem.github.io/horizontes/jogo_b.html'],['jogo-c','Dominó das Frações','https://neilasalem.github.io/horizontes/jogo_c.html'],['jogo-d','Frações no Cotidiano','https://neilasalem.github.io/horizontes/jogo_d.html'],['guia','Guia por rubrica','https://furukawaluzia-lt1.github.io/tutor-fracoes-rubrica/']];
const el=id=>document.getElementById(id);let report=null,external=null;
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());el('to').value=today;el('from').value='2026-10-05';el('flipFrom').value='2026-10-05';el('flipTo').value=today;
function time(ms){let s=Math.round(ms/1000);return s>=60?`${Math.floor(s/60)}min ${s%60}s`:`${s}s`}
function sum(rows,k){return rows.reduce((n,r)=>n+Number(r[k]||0),0)}
function render(){
 const body=el('sources');body.replaceChildren();
 for(const [id,name,url]of MATERIALS){const rows=report?report.rows.filter(r=>r.page===id):[];const v=sum(rows,'views'),ms=sum(rows,'active_ms'),p=sum(rows,'prints');const st=report?.status.find(s=>s.page===id);const tr=document.createElement('tr');const label=document.createElement('td');const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent=name;label.append(a);const desc=document.createElement('small');desc.textContent=id==='guia'?'Tempo ativo · botão de impressão':'Tempo ativo · abertura por carregamento';label.append(desc);tr.append(label);for(const text of [report?v:'—',v?time(ms/v):'—',id==='guia'?(report?p:'—'):'—']){const td=document.createElement('td');td.textContent=text;tr.append(td)}const status=document.createElement('td');const tag=document.createElement('span');tag.className='status'+(st?' active':'');tag.textContent=st?'Dados recebidos':'Aguardando instalação / primeiro acesso';status.append(tag);tr.append(status);body.append(tr)}
 const views=report?sum(report.rows,'views'):0;el('views').textContent=report?views.toLocaleString('pt-BR'):'—';el('avg').textContent=views?time(sum(report.rows,'active_ms')/views):'—';el('engaged').textContent=views?`${Math.round(sum(report.rows,'over_30s')/views*100)}%`:'—';el('prints').textContent=report?sum(report.rows.filter(r=>r.page==='guia'),'prints'):'—';
 const chart=el('chart');chart.replaceChildren();const days={};for(const r of report?.rows||[])days[r.day]=(days[r.day]||0)+Number(r.views);const max=Math.max(1,...Object.values(days));for(const day of Object.keys(days).sort()){let bar=document.createElement('div');bar.className='bar';let val=document.createElement('b');val.textContent=days[day];let block=document.createElement('div');block.style.height=(days[day]/max*115)+'px';let label=document.createElement('span');label.textContent=day.slice(8)+'/'+day.slice(5,7);bar.title=`${day}: ${days[day]} aberturas`;bar.append(val,block,label);chart.append(bar)}if(!Object.keys(days).length)chart.textContent=report?'Sem acessos registrados neste período.':'Dados ainda indisponíveis.';
 if(external){const inPeriod=external.from>=el('from').value&&external.to<=el('to').value;el('flipResult').textContent=`${external.from} a ${external.to}: ${external.views} aberturas · ${time(external.minutes*60000)} de duração total · média ${external.views?time(external.minutes*60000/external.views):'não calculável'}. ${inPeriod?'Incluído na exportação, com métrica própria.':'Fora do período selecionado: não será exportado.'}`}
}
async function load(){if(el('from').value>el('to').value){el('message').textContent='A data inicial deve ser anterior ou igual à final.';return}el('message').textContent='Atualizando dados compartilhados…';try{const u=new URL(ENDPOINT);u.searchParams.set('from',el('from').value);u.searchParams.set('to',el('to').value);const response=await fetch(u,{credentials:'omit',cache:'no-store'});if(!response.ok)throw Error('Falha de consulta');const data=await response.json();if(!Array.isArray(data.rows)||!Array.isArray(data.status))throw Error('Resposta inválida');report=data;el('message').textContent=data.rows.length?'Dados reais da coleta instalada. O FlipHTML5 tem registro próprio abaixo.':'Serviço conectado, sem acessos recebidos neste período. Fontes ainda sem instalação não representam zero visitantes.';el('updated').textContent='Atualizado em '+new Date(data.generated_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'});}catch{report=null;el('message').textContent='Não foi possível consultar a coleta. Nenhum número foi estimado. Tente atualizar em alguns instantes.';el('updated').textContent='Consulta indisponível'}render()}
el('filters').addEventListener('submit',e=>{e.preventDefault();load()});el('flipForm').addEventListener('submit',e=>{e.preventDefault();const from=el('flipFrom').value,to=el('flipTo').value,views=Number(el('flipViews').value),minutes=Number(el('flipMinutes').value);if(from>to||!Number.isSafeInteger(views)||views<0||!Number.isFinite(minutes)||minutes<0){el('flipResult').textContent='Confira as datas e os números informados.';return}external={from,to,views,minutes};render()});
el('export').addEventListener('click',()=>{const rows=[['inicio','fim','material','aberturas','tempo_total_segundos','impressoes_solicitadas','metrica','fuso']];if(report)for(const r of report.rows)rows.push([r.day,r.day,r.page,r.views,Number(r.active_ms)/1000,r.prints,'tempo_visivel_com_foco','America/Sao_Paulo']);if(external&&external.from>=el('from').value&&external.to<=el('to').value)rows.push([external.from,external.to,'fliphtml5-vtse',external.views,external.minutes*60,'','duracao_nativa_fliphtml5','UTC+4']);if(rows.length===1){el('message').textContent='Não há dados disponíveis para exportar.';return}const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='relatorio-uso-professor-tutor.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});render();load();
